#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: PolicySeq
apiVersion: api.webmethods.io/beta
metadata:
  name: policy_sequence
  version: 1.0
  namespace: sample
  tags:
    - dev_policies
spec: #Lists all the stages with policies in each of them
    transport:
      - $ref: sample:transport_protocol:1.0
    iam:
      - $ref: sample:identify_and_authorize:1.0
    monitoring: 
      - $ref: sample:log_invocation:1.0
    routing:
      - $ref: sample:straight-through-routing:1.0
    # error-handling:
    #   - $ref: sample:conditional_error_processing:1.0