kind: assertion
apiVersion: api.ibm.com/v1
metadata:
  name: GET-store-order-0-400
  namespace: issue0check
  version: '1.0'
  tags: []
  description: ''
spec:
  - name: Validate the response status code
    key: responseStatus
    value: 400
    action: equals
    stopOnFail: false
