kind: IdentifyAndAuthorize
apiVersion: api.webmethods.io/beta
metadata: 
    name: MyIAM
    version: '1.0'
    namespace: 'cli'
    tags:
      - iam
spec: 
  enabled: true
  triggerPolicyViolation: true
  identificationType:
    or:
      apiKey:
        applicationLookup: 'registered'
      httpBasicAuth:
        applicationLookup: 'registered'
