kind: PolicySequence
apiVersion: api.webmethods.io/beta
metadata: 
    name: policySeq
    version: 1.0
    namespace: cli
spec:
    transport:
      - $ref: cli:transportPolicy:1.0
    iam:
      - $ref: cli:MyIAM:1.0
    routing:
      - $ref: cli:routing:1.0