kind: test
apiVersion: api.webmethods.io/beta
metadata:
  name: TestPaymentsviki
  version: 1.0.0
  tags:
    - functional
  namespace: default
spec:
  api:
    $endpoint: 'https://petstore.swagger.io/v2'
  environment:
    $ref: defaultViki:testViki:1.0.1
  request:
    - method: GET
      resource: /pet/13
      headers:
        - key: Content-Type
          value: application/json
        - key: X-Gateway-APIKey
          value: ${apiKey}
      auth:
        noauth: true

      settings:
        sslVerification: false
        encodeURL: true
      assertions:
        $ref: default:testAssertion:1.0.0
