#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
---
kind: Transport
apiVersion: api.webmethods.io/beta
metadata:
  name: transport_protocol
  version: 1.0
  namespace: sample
spec: 
    protocol:
      - http
      - https